### ISSUE TITLE
Add a gender value "diverse"

### ISSUE THREAD

**Issue by fennecgit** [oliverklee/ext-feuserextrafields#239]
Please include the option "divers" for the field gender in TCA.
The same should be considered in model (see `public const VALID_GENDERS = [self::GENDER_MALE, self::GENDER_FEMALE, self::GENDER_NOT_PROVIDED];`).

Thank you in advance.

**Comment by oliverklee** [comment]
Thanks for the suggestion!

Do you know any other extensions that already do this so we can have a gender code (the integer that is represented by the constants) that is as compatible as possible?

**Comment by oliverklee** [comment]
I've also created a corresponding issue for my onetimeaccount extension: https://github.com/oliverklee/ext-onetimeaccount/issues/529

**Comment by oliverklee** [comment]
Some research:
- fp_newsletter uses a completely different numbering scheme: https://github.com/bihor/fp_newsletter/blob/master/Classes/Controller/LogController.php#L126
- modules uses string constants: male, female, family, diverse
- femanager uses 2: https://github.com/in2code-de/femanager/blob/develop/Resources/Private/Language/locallang.xlf#L48
- sr_feuser_register does not have "divers" yet.

So I'll probably go with 2 for "divers".

**Comment by fennecgit** [comment]
Yes, 2 for divers is perfect! I use seminars extension and femanger.

Thank you!

**Comment by oliverklee** [comment]
The implementation for oelib is done now: https://github.com/oliverklee/ext-oelib/pull/1288

**Comment by oliverklee** [comment]
The implementation for onetimeaccount: https://github.com/oliverklee/ext-onetimeaccount/pull/566
